### PR TITLE
Ensure cached env not written when remember flag off

### PR DESCRIPTION
**Pull request by robertzk**
@birdandbees

### CODE REVIEW

**Comment by robertzk** [comment]
Looking at this now.

**Comment by robertzk** [comment]
The issue is a little more complicated than I originally thought. Will continue working on this at the end of the day.

**Comment by robertzk** [comment]
Couple more hrs when I can revisit this.

**Comment by birdandbees** [comment]
This one is good to go. slightly over raw data * 2

**Comment by robertzk** [comment]
Great, fixing tests now.

**Comment by tonglu** [comment]
@robertzk if you are too busy, maybe @kirillseva can give it a shot?

**Comment by tonglu** [comment]
@robertzk @birdandbees tests are still broken

**Comment by kirillseva** [comment]
They pass locally. Rn debugging Travis-CI

**Comment by robertzk** [comment]
I've narrowed it down a problem with purrr but not sure exactly how yet.

**Comment by kirillseva** [comment]
@robertzk same failures....

**Pull request merged**
